/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinanzas.interfaz;

import com.mycompany.proyectofinanzas.controlador.InterfazControlador;
import com.mycompany.proyectofinanzas.servicios.MovimientoServicio;
import com.mycompany.proyectofinanzas.servicios.UsuarioServicios;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo
 */
public class IngresarMovimiento extends javax.swing.JFrame {
    private InterfazControlador controlador;
    private UsuarioServicios usuarioActualC;
    private MovimientoServicio movimientoUsuario;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IngresarMovimiento.class.getName());

    /**
     * Creates new form IngresarMovimiento
     */
    public IngresarMovimiento(InterfazControlador controlador, UsuarioServicios usuarioActualC,MovimientoServicio movimientoUsuario) {
        initComponents();
        this.controlador = controlador;
        this.usuarioActualC = usuarioActualC;
        this.movimientoUsuario = movimientoUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        seleccionDeTipoDeMovi = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        movimientoCantidad = new javax.swing.JTextPane();
        menuMovimientoVolver = new javax.swing.JButton();
        registrarMovimiento = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcionMoviomiento = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Movimientos");

        seleccionDeTipoDeMovi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Gastos", "Ingreso" }));
        seleccionDeTipoDeMovi.addActionListener(this::seleccionDeTipoDeMoviActionPerformed);

        jLabel2.setText("Ingrese el tipo de movimiento");

        jLabel3.setText("Ingrese la cantidad del movimiento(sin puntos o comas)");

        jScrollPane1.setViewportView(movimientoCantidad);

        menuMovimientoVolver.setText("Volver");
        menuMovimientoVolver.addActionListener(this::menuMovimientoVolverActionPerformed);

        registrarMovimiento.setText("Registrar movimiento");
        registrarMovimiento.addActionListener(this::registrarMovimientoActionPerformed);

        jLabel4.setText("Descripción del movimiento");

        descripcionMoviomiento.setColumns(20);
        descripcionMoviomiento.setRows(5);
        jScrollPane2.setViewportView(descripcionMoviomiento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(registrarMovimiento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(menuMovimientoVolver)
                                .addGap(9, 9, 9))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seleccionDeTipoDeMovi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccionDeTipoDeMovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuMovimientoVolver)
                    .addComponent(registrarMovimiento))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionDeTipoDeMoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionDeTipoDeMoviActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionDeTipoDeMoviActionPerformed

    private void menuMovimientoVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMovimientoVolverActionPerformed
        // TODO add your handling code here:
        controlador.volverMenuInicialIngre();
    }//GEN-LAST:event_menuMovimientoVolverActionPerformed

    private void registrarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMovimientoActionPerformed
        // TODO add your handling code here:
        String usuario = usuarioActualC.getUsuario();
        String tipoDeMovimiento = seleccionDeTipoDeMovi.getSelectedItem().toString();
        String text2 = movimientoCantidad.getText();
        String descripcion  = descripcionMoviomiento.getText();
        
        if(tipoDeMovimiento.equals("Seleccione una opcion")){
            JOptionPane.showMessageDialog(null, "Seleccione un tipo de movimiento.", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(tipoDeMovimiento.equals("Seleccione una opcion") || text2.isEmpty() || descripcion.isEmpty()){
            JOptionPane.showMessageDialog(null, "Opciones no digitadas o seleccionadas", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
           double monto = Double.parseDouble(text2);
           movimientoUsuario.guardarMovimeinto(usuario, tipoDeMovimiento, monto, descripcion);
           JOptionPane.showMessageDialog(null, "Movimiento guardado correctamente.");
           descripcionMoviomiento.setText("");
           movimientoCantidad.setText("");
        }
           
        
    }//GEN-LAST:event_registrarMovimientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descripcionMoviomiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton menuMovimientoVolver;
    private javax.swing.JTextPane movimientoCantidad;
    private javax.swing.JButton registrarMovimiento;
    private javax.swing.JComboBox<String> seleccionDeTipoDeMovi;
    // End of variables declaration//GEN-END:variables
}
