/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinanzas.interfaz;

import com.mongodb.client.MongoClient;
import com.mycompany.proyectofinanzas.baseDeDatos.BaseDeDatos;
import com.mycompany.proyectofinanzas.controlador.InterfazControlador;
import com.mycompany.proyectofinanzas.repositorio.RepositorioUsuario;
import com.mycompany.proyectofinanzas.servicios.UsuarioServicios;
import javax.swing.JOptionPane;


/**
 *
 * @author Pablo
 */
public class Inicio extends javax.swing.JFrame {
    
    private final InterfazControlador controlador;
    private RepositorioUsuario controladorDB;
    private UsuarioServicios servicio;
    MongoClient client = BaseDeDatos.accesoConexion();
    
    /**
     * Creates new form Inicio
     * @param controlador
     */
    public Inicio(InterfazControlador controlador, RepositorioUsuario controladorDB, UsuarioServicios servicio) {
        initComponents();
        this.controlador = controlador;
        this.controladorDB = controladorDB;
        this.servicio = servicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnFormRegis = new javax.swing.JButton();
        btnIniSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingresoUsuario = new javax.swing.JTextPane();
        ingresoContra = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");

        jLabel2.setText("Ingrese su usuario");

        jLabel3.setText("Ingrese su contraseña");

        btnLogin.setText("Ingresar");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        btnFormRegis.setText("Registrar");
        btnFormRegis.addActionListener(this::btnFormRegisActionPerformed);

        btnIniSalir.setText("Salir");
        btnIniSalir.addActionListener(this::btnIniSalirActionPerformed);

        jScrollPane1.setViewportView(ingresoUsuario);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Controlgast");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLogin)
                                .addGap(18, 18, 18)
                                .addComponent(btnFormRegis)
                                .addGap(18, 18, 18)
                                .addComponent(btnIniSalir))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(ingresoContra)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(ingresoContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnFormRegis)
                    .addComponent(btnIniSalir))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnIniSalirActionPerformed

    private void btnFormRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormRegisActionPerformed
        // TODO add your handling code here:
        controlador.mostrarFormularioDeRegistro();
        ingresoContra.setText("");
        ingresoUsuario.setText("");
    }//GEN-LAST:event_btnFormRegisActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String usuario = ingresoUsuario.getText();
        String password = new String(ingresoContra.getPassword());
        controladorDB.ingresoLogin(usuario, password);

        boolean acceso = servicio.login(usuario, password);

        if (acceso) {
            controlador.setUsuarioLogueado(usuario);
            controlador.menuIngreso();
            JOptionPane.showMessageDialog(null, "Bienvenido " + servicio.getUsuario());
        } else {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        ingresoContra.setText("");
        ingresoUsuario.setText("");
    }//GEN-LAST:event_btnLoginActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormRegis;
    private javax.swing.JButton btnIniSalir;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPasswordField ingresoContra;
    private javax.swing.JTextPane ingresoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
