/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinanzas.interfaz;

import com.mycompany.proyectofinanzas.controlador.InterfazControlador;

/**
 *
 * @author Pablo
 */
public class MenuInicialUsuario extends javax.swing.JFrame {
    private final InterfazControlador controlador;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuInicialUsuario.class.getName());

    /**
     * Creates new form MenuInicialUsuario
     */
    public MenuInicialUsuario(InterfazControlador controlador) {
        this.controlador = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        registrarMeta = new javax.swing.JButton();
        ingresarMovimiento = new javax.swing.JButton();
        verProgreso = new javax.swing.JButton();
        verSimulacion = new javax.swing.JButton();
        salirMenuInicial = new javax.swing.JButton();
        verMovimientos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Controlgast");

        jLabel2.setText("Menu de usuario");

        registrarMeta.setText("Registrar una meta");
        registrarMeta.addActionListener(this::registrarMetaActionPerformed);

        ingresarMovimiento.setText("Ingresar movimientos");
        ingresarMovimiento.addActionListener(this::ingresarMovimientoActionPerformed);

        verProgreso.setText("Ver progreso de mi meta");
        verProgreso.addActionListener(this::verProgresoActionPerformed);

        verSimulacion.setText("Simulador de inversion");
        verSimulacion.addActionListener(this::verSimulacionActionPerformed);

        salirMenuInicial.setText("Salir");
        salirMenuInicial.addActionListener(this::salirMenuInicialActionPerformed);

        verMovimientos.setText("Ver movimientos");
        verMovimientos.addActionListener(this::verMovimientosActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(registrarMeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ingresarMovimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(verProgreso, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(verSimulacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(verMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salirMenuInicial))))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(registrarMeta)
                .addGap(18, 18, 18)
                .addComponent(ingresarMovimiento)
                .addGap(18, 18, 18)
                .addComponent(verProgreso)
                .addGap(18, 18, 18)
                .addComponent(verSimulacion)
                .addGap(18, 18, 18)
                .addComponent(verMovimientos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(salirMenuInicial)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verMovimientosActionPerformed
        // TODO add your handling code here:
        controlador.mostrarMovimientos();
    }//GEN-LAST:event_verMovimientosActionPerformed

    private void salirMenuInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuInicialActionPerformed
        // TODO add your handling code here:
        controlador.deslogueo();
    }//GEN-LAST:event_salirMenuInicialActionPerformed

    private void registrarMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMetaActionPerformed
        // TODO add your handling code here:
        controlador.mostrarMeta();
    }//GEN-LAST:event_registrarMetaActionPerformed

    private void ingresarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarMovimientoActionPerformed
        // TODO add your handling code here:
        controlador.mostrarMenuIngreso();
    }//GEN-LAST:event_ingresarMovimientoActionPerformed

    private void verProgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verProgresoActionPerformed
        // TODO add your handling code here:
        controlador.mostrarProgreso();
    }//GEN-LAST:event_verProgresoActionPerformed

    private void verSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verSimulacionActionPerformed
        // TODO add your handling code here:
        controlador.mostrarSimulacion();
    }//GEN-LAST:event_verSimulacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ingresarMovimiento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registrarMeta;
    private javax.swing.JButton salirMenuInicial;
    private javax.swing.JButton verMovimientos;
    private javax.swing.JButton verProgreso;
    private javax.swing.JButton verSimulacion;
    // End of variables declaration//GEN-END:variables
}
