/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinanzas.interfaz;

import com.mycompany.proyectofinanzas.controlador.InterfazControlador;
import com.mycompany.proyectofinanzas.servicios.MovimientoServicio;
import com.mycompany.proyectofinanzas.servicios.UsuarioServicios;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo
 */
public class MetaUsuario extends javax.swing.JFrame {
    
    private final InterfazControlador controlador;
    private final UsuarioServicios servicio;
    private final MovimientoServicio movimientoUsuario;
    /**
     * Creates new form MetaUsuario
     * @param controlador
     * @param servicio
     * @param movimientoUsuario
     */
    public MetaUsuario(InterfazControlador controlador, UsuarioServicios servicio,MovimientoServicio movimientoUsuario) {
        initComponents();
        this.controlador = controlador;
        this.servicio = servicio;
        this.movimientoUsuario = movimientoUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        metaCantidad = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        metaTiempo = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        metaIngresos = new javax.swing.JTextPane();
        btnMenuMetaVolver = new javax.swing.JButton();
        registrarMeta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        metaGastos = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        nombreMeta = new javax.swing.JTextPane();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de META");

        jLabel2.setText("Ingrese la meta a la que quiere llegar(sin comas o puntos)");

        jScrollPane1.setViewportView(metaCantidad);

        jLabel3.setText("Ingrese el timpo en meses. (Ej: 2 meses)");

        jScrollPane2.setViewportView(metaTiempo);

        jLabel4.setText("Ingrese sus ingresos mensuales totales (sin comas o puntos)");

        jScrollPane3.setViewportView(metaIngresos);

        btnMenuMetaVolver.setText("Volver");
        btnMenuMetaVolver.addActionListener(this::btnMenuMetaVolverActionPerformed);

        registrarMeta.setText("Registrar meta");
        registrarMeta.addActionListener(this::registrarMetaActionPerformed);

        jLabel5.setText("Ingrese gastos totales del mes (sin comas o puntos)");

        jScrollPane4.setViewportView(metaGastos);

        jLabel6.setText("Nombre de su meta:");

        jScrollPane5.setViewportView(nombreMeta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(registrarMeta)
                        .addGap(135, 135, 135)
                        .addComponent(btnMenuMetaVolver))
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5)))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenuMetaVolver)
                    .addComponent(registrarMeta))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuMetaVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMetaVolverActionPerformed
        // TODO add your handling code here:
        controlador.volverMenuInicialmeta();
    }//GEN-LAST:event_btnMenuMetaVolverActionPerformed

    private void registrarMetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMetaActionPerformed
        // TODO add your handling code here:
        String usuarioActual = servicio.getUsuario();
        
        if(metaCantidad.getText().isEmpty() || metaTiempo.getText().isEmpty() || metaIngresos.getText().isEmpty() || metaGastos.getText().isEmpty() || nombreMeta.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor dijite todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            String capturaDeTiempo = metaTiempo.getText().toLowerCase();
            StringBuilder soloNumeros = new StringBuilder();
            for(int i =0; i<capturaDeTiempo.length();i++){
                char caracterActual = capturaDeTiempo.charAt(i);
                if(Character.isDigit(caracterActual)){
                    soloNumeros.append(caracterActual);
                }
                if(caracterActual == 'a'){
                    JOptionPane.showMessageDialog(null, "El timpo que estas intento ingresar no es en meses, por favor solo intente con meses.","Error", JOptionPane.ERROR_MESSAGE);
                    soloNumeros.setLength(0);
                    return;
                }
            }
            double valorMeta = Double.parseDouble(metaCantidad.getText());
            int timpoDemeta = Integer.parseInt(soloNumeros.toString());
            double ingresosParaMeta = Double.parseDouble(metaIngresos.getText());
            double gastosParaMeta = Double.parseDouble(metaGastos.getText());
            String nombreDeMeta = nombreMeta.getText();
            
            double metaDiferida = (valorMeta/timpoDemeta);
            double capacidadDeAhorro = (ingresosParaMeta-gastosParaMeta);
            if(valorMeta <= 0){
                JOptionPane.showMessageDialog(null, "El valor de la meta no puede ser 0","Error", JOptionPane.ERROR_MESSAGE);
            }else if(timpoDemeta <= 0){
                JOptionPane.showMessageDialog(null, "El tiempo de la meta no puede ser 0","Error", JOptionPane.ERROR_MESSAGE);
            }else if(ingresosParaMeta <= 0){
                JOptionPane.showMessageDialog(null, "Sin ingresos no podras cumplir la meta","Error", JOptionPane.ERROR_MESSAGE);
            }else if(metaDiferida > capacidadDeAhorro){
                JOptionPane.showMessageDialog(null, "La meta no sera posible completarla en ese tiempo, favor incremente los meses","Error", JOptionPane.ERROR_MESSAGE);
            }else{
                movimientoUsuario.cargarMetaAUsuario(usuarioActual, nombreDeMeta, valorMeta, timpoDemeta, ingresosParaMeta, gastosParaMeta);
                JOptionPane.showMessageDialog(null, "Meta cargada :)");
                metaCantidad.setText("");
                metaTiempo.setText("");
                metaIngresos.setText("");
                metaGastos.setText("");
                nombreMeta.setText("");
            }
        }
    }//GEN-LAST:event_registrarMetaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuMetaVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane metaCantidad;
    private javax.swing.JTextPane metaGastos;
    private javax.swing.JTextPane metaIngresos;
    private javax.swing.JTextPane metaTiempo;
    private javax.swing.JTextPane nombreMeta;
    private javax.swing.JButton registrarMeta;
    // End of variables declaration//GEN-END:variables
}
