/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinanzas.interfaz;

import com.mycompany.proyectofinanzas.controlador.InterfazControlador;
import com.mycompany.proyectofinanzas.repositorio.RepositorioMovimiento;
import com.mycompany.proyectofinanzas.servicios.MovimientoServicio;
import com.mycompany.proyectofinanzas.servicios.UsuarioServicios;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author Pablo
 */
public class MovimientoUsuario extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MovimientoUsuario.class.getName());
    private InterfazControlador controlador;
    private UsuarioServicios usuarioSer;
    private MovimientoServicio servicioMo;
    private RepositorioMovimiento repoMo;

    /**
     * Creates new form MovimientoUsuario
     */
    public MovimientoUsuario(InterfazControlador controlador, UsuarioServicios usuarioSer, MovimientoServicio servicioMo) {
        initComponents();
        this.controlador = controlador;
        this.usuarioSer = usuarioSer;
        this.servicioMo = servicioMo;

        configurarTabla();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        editarMovimiento = new javax.swing.JButton();
        eliminarMovimiento = new javax.swing.JButton();
        movimientoVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Movimientos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tipo", "Monto", "Descripcion"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Movimientos:");

        editarMovimiento.setText("Editar");
        editarMovimiento.addActionListener(this::editarMovimientoActionPerformed);

        eliminarMovimiento.setText("Eliminar");
        eliminarMovimiento.addActionListener(this::eliminarMovimientoActionPerformed);

        movimientoVolver.setText("Volver");
        movimientoVolver.addActionListener(this::movimientoVolverActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(movimientoVolver)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(editarMovimiento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                            .addComponent(eliminarMovimiento))
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarMovimiento)
                    .addComponent(eliminarMovimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(movimientoVolver)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("ID");
        modelo.addColumn("Tipo");
        modelo.addColumn("Monto");
        modelo.addColumn("Descripción");

        jTable1.setModel(modelo);
    }
    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
        if (visible) {
            cargarTablaMovimientos(); // ✅ se ejecuta con el usuario ya logueado
        }
    }

    public void cargarTablaMovimientos() {
        String usuario = usuarioSer.getUsuario();
        System.out.println(">>> Usuario en tabla: " + usuario); // debug temporal

        if (usuario == null || usuario.isEmpty()) {
            return; // silencioso, sin JOptionPane
        }

        List<Document> lista = servicioMo.obtenerMovimientosPorUsuario(usuario);
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        for (Document doc : lista) {
            modelo.addRow(new Object[]{
                doc.getObjectId("_id").toString(),
                doc.getString("tipoDeMovimiento"),
                ((Number) doc.get("monto")).doubleValue(),
                doc.getString("descripcion")
            });
        }
    }
    private void movimientoVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movimientoVolverActionPerformed
        // TODO add your handling code here:
        controlador.volverMenuInicialMovimi();
    }//GEN-LAST:event_movimientoVolverActionPerformed

    private void editarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarMovimientoActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un movimiento");
            return;
        }

        String id = jTable1.getValueAt(fila, 0).toString();

        String tipo = jTable1.getValueAt(fila, 1).toString();
        double monto = (Double) jTable1.getValueAt(fila, 2);
        String descripcion = jTable1.getValueAt(fila, 3).toString();

        // Ejemplo simple (puedes mejorar con inputs)
        servicioMo.actualizarMovimiento(id, tipo, monto, descripcion);

        cargarTablaMovimientos();
    }//GEN-LAST:event_editarMovimientoActionPerformed

    private void eliminarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMovimientoActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un movimiento");
            return;
        }

        String id = jTable1.getValueAt(fila, 0).toString();

        servicioMo.eliminarMovimiento(id);

        cargarTablaMovimientos();
    }//GEN-LAST:event_eliminarMovimientoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();

        if (fila != -1) {
            // Obtener datos actuales desde la tabla
            String id = jTable1.getValueAt(fila, 0).toString();
            String tipo = jTable1.getValueAt(fila, 1).toString();
            Double monto = (Double) jTable1.getValueAt(fila, 2);
            String descripcion = jTable1.getValueAt(fila, 3).toString();

            //Pedir nuevos datos (con valores actuales por defecto)
            String nuevoTipo = JOptionPane.showInputDialog("Nuevo tipo:", tipo);
            String nuevoMontoStr = JOptionPane.showInputDialog("Nuevo monto:", monto);
            String nuevaDescripcion = JOptionPane.showInputDialog("Nueva descripción:", descripcion);

            // Convertir monto
            double nuevoMonto = Double.parseDouble(nuevoMontoStr);

            // Actualizar en BD
            servicioMo.actualizarMovimiento(id, nuevoTipo, nuevoMonto, nuevaDescripcion);

            // Recargar tabla
            cargarTablaMovimientos();
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarMovimiento;
    private javax.swing.JButton eliminarMovimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton movimientoVolver;
    // End of variables declaration//GEN-END:variables
}
