/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinanzas.interfaz;

import com.mycompany.proyectofinanzas.controlador.InterfazControlador;
import com.mycompany.proyectofinanzas.servicios.MovimientoServicio;
import com.mycompany.proyectofinanzas.servicios.UsuarioServicios;
import java.util.List;
import javax.swing.JOptionPane;
import org.bson.Document;

/**
 *
 * @author Pablo
 */
public class VerProgresoDeMeta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VerProgresoDeMeta.class.getName());
    private InterfazControlador controlador;
    private UsuarioServicios usuarioSer;
    private MovimientoServicio movimientoSer;
    /**
     * Creates new form VerProgresoDeMeta
     */
    public VerProgresoDeMeta(InterfazControlador controlador,UsuarioServicios usuarioSer,MovimientoServicio movimientoSer) {
        initComponents();
        this.controlador = controlador;
        this.usuarioSer = usuarioSer;
        this.movimientoSer = movimientoSer;
        
        seleccionDeMeta.addActionListener(e -> barraPorcentaje());
    }
    
    @Override
    public void setVisible(boolean visible) {
        if (visible) {
            cargarDatosDeMetasOpcion();
        }
        super.setVisible(visible);
    }

    
    public void cargarDatosDeMetasOpcion(){
        String usuario = usuarioSer.getUsuario();
        logger.info(">>> cargarDatosDeMetasOpcion - usuario obtenido: '" + usuario + "'");

        if (usuario == null || usuario.trim().isEmpty()) {
            logger.warning(">>> El usuario es null o vacío. No se pueden cargar metas.");
            seleccionDeMeta.removeAllItems();
            seleccionDeMeta.addItem("Error: usuario no disponible.");
            return;
        }

        List<Document> metas = movimientoSer.obtenerMetaDeUsuario(usuario.trim());
        logger.info(">>> Metas encontradas en BD: " + metas.size());

        for (Document d : metas) {
            logger.info(">>> Documento completo: " + d.toJson());
        }

        seleccionDeMeta.removeAllItems();

        if (metas.isEmpty()) {
            seleccionDeMeta.addItem("No hay metas disponibles.");
            return;
        }

        for (Document meta : metas) {
            String nombre = meta.getString("nombreDeMeta");
            logger.info(">>> nombreDeMeta leído: '" + nombre + "'");
            seleccionDeMeta.addItem(nombre != null ? nombre : "(sin nombre)");}
    }
    
    public void barraPorcentaje(){
        
        String nombreMetaSeleccionada = (String) seleccionDeMeta.getSelectedItem();
        if(nombreMetaSeleccionada == null || nombreMetaSeleccionada.equals("No hay metas disponibles")){
            return;
        }
        
        String usuario = usuarioSer.getUsuario();

        
        List<Document> metas = movimientoSer.obtenerMetaDeUsuario(usuario);
        int cantidadMetas = metas.size();
        
        if(cantidadMetas == 0){
            return;
        }
        
        for(Document meta : metas){
            if(nombreMetaSeleccionada.equals(meta.getString("nombreDeMeta"))){
                double valorDeMeta = meta.getDouble("valorMeta");
                double totalIngresos = movimientoSer.obtenerTotalDeSumaDeIngresos(usuario);
                double totalEgresos = movimientoSer.obtenerTotalDeSumaDeEgresos(usuario);
               
                double balance = totalIngresos - totalEgresos;
                double divirIngresosEnMetas = Math.max(balance, 0) / cantidadMetas;
                
                double poncentajeDeMeta = (divirIngresosEnMetas / valorDeMeta)*100;
                int progreso = (int) Math.min((int) Math.max(poncentajeDeMeta, 0), 100);
                
                barraDeProgreso.setValue(progreso);
                MensajeMeta.setText("Porcentaje de su meta es: "+ progreso+"%");
                    JOptionPane.showMessageDialog(null, "Felicitraciones, meta alcanzada :)");
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        barraDeProgreso = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        seleccionDeMeta = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        MensajeMeta = new javax.swing.JLabel();
        procesoMetaVolver = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Progreso de meta");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        seleccionDeMeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "selecciones una opcion" }));

        jLabel2.setText("Seleccione una meta a visualizar");

        MensajeMeta.setText("Porcentaje de su meta es: ");

        procesoMetaVolver.setText("Volver");
        procesoMetaVolver.addActionListener(this::procesoMetaVolverActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(procesoMetaVolver)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seleccionDeMeta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addComponent(barraDeProgreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MensajeMeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccionDeMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(barraDeProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MensajeMeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(procesoMetaVolver)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void procesoMetaVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesoMetaVolverActionPerformed
        // TODO add your handling code here:
        controlador.volverMenuInicialPro();
    }//GEN-LAST:event_procesoMetaVolverActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MensajeMeta;
    private javax.swing.JProgressBar barraDeProgreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton procesoMetaVolver;
    private javax.swing.JComboBox<String> seleccionDeMeta;
    // End of variables declaration//GEN-END:variables
}
